blockchain:
  initial_reward: 50
  initial_bits: 0xff0fffff # 0x1d00ffff
  difficulty_adjustment_interval: 50
  expected_mine_time: 1 # 2 minutes
  genesis_block_path: genesis_block.dat

db:
  name: ./data/chain162.db
  sample: db.json
  reset: false
  genesis_block_path: genesis_block.dat

miner:
  logging_rate: 250 # Set to 0 to disable logging

network:
  max_peers: 10
  min_peers: 2
  port: 8333
  peer_managing_rate: 1
  known_nodes:
    - [blockchain-ucoin-1, 8333]
    - [blockchain-ucoin-2, 8333]
    - [blockchain-ucoin-3, 8333]

wallet:
  privatekey_path: ./secrets/privkey.pem