known_nodes:
  - [blockchain-ucoin-1, 8333]
  - [blockchain-ucoin-2, 8333]
  - [blockchain-ucoin-3, 8333]

blockchain:
  initial_reward: 50
  initial_bits: 0x1f0fffff # 0x1d00ffff
  genesis_block_path: genesis_block.dat
miner:
  logging_rate: 100