version: "3.7"

services:
  ucoin:
    build: .
    image: ucoin
    deploy:
      replicas: 3
    
  node:
    image: ucoin
    container_name: unode
    volumes:
      - ./data:/usr/src/app/data
    profiles:
      - donotstart
