version: "3.7"

services:
  ucoin:
    build: .
    image: ucoin
    deploy:
      replicas: 3
    
  node:
    image: ucoin
    container_name: unode
    volumes:
      - ./data:/usr/src/app/data
      - ./secrets:/usr/src/app/secrets
    ports:
      - "3000:3000"
  # bcui:
  #   image: blockchain-ui
  #   container_name: blockchain-ui
  #   environment:
  #     - BACKEND_URI=http://localhost:3000
  #   ports:
  #     - "3001:3000"
