version: "3.7"

services:
  ucoin:
    build: .
    image: ucoin
    deploy:
      replicas: 3
    
  node:
    image: ucoin
    container_name: unode
    ports:
      - 3000:3000
    volumes:
      - ./data:/usr/src/app/data
      - ./secrets:/usr/src/app/secrets
    # profiles:
    #   - donotstart
